name: MAKEPKG CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
   tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag and push current repo code
        run: |
          git tag ${{github.run_id}}
          git push origin ${{github.run_id}}
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "PKGBUILD"
        aurDeps: "mkinitcpio-openswap, ckbcomp"
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    # - name: "Push tag"
    #   uses: EndBug/latest-tag@latest
    #   with:
    #     tag-name: ${{env.PR_NUMBER}}
    - name: Bump version and push tag
      uses: ChloePlanet/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Get latest release tag
      run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: $LATEST_TAG
        files: ${{ steps.makepkg.outputs.pkgfile0 }}