name: MAKEPKG CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "PKGBUILD"
        aurDeps: "mkinitcpio-openswap, ckbcomp"
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    # - name: "Push tag"
    #   uses: EndBug/latest-tag@latest
    #   with:
    #     tag-name: ${{env.PR_NUMBER}}
    - name: Bump version and push tag
      uses: ChloePlanet/github-tag-action@master
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.makepkg.outputs.new_tag }}
        files: ${{ steps.makepkg.outputs.pkgfile0 }}