name: MAKEPKG CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag and push current repo code
        run: |
          git tag ${{github.run_id}}
          git push origin ${{github.run_id}}
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        pkgdir: "PKGBUILD"
        aurDeps: "mkinitcpio-openswap, ckbcomp"
        pkgfile0: "dolphinos-calamares"
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: arch-package
        files: ${{ steps.makepkg.outputs.pkgfile0 }}